export const EasyWords: string[] = [
	"crossfaith",
	"Sugarcult",
	"SUM 41",
	"coldrain",
	"SiM",
	"Azami",
	"SHANK",
	"サカナクション",
	"ストレイテナー",
	"SHADOWS",
	"ONEOKROCK",
	"MY FIRST STORY",
	"凛として時雨",
	"The BONEZ",
	"MONOEYES",
	"ELLEGARDEN",
	"10-FEET",
	"foobastank",
	"そこに鳴る",
	"東京事変",
];

export const HardWords: string[] = [
	"Fear Lothing in Lasvegas",
	"While She Sleeps",
	"maximum the hormone",
	"04LimitedSazabys",
	"八十八か所巡礼",
	"ヤバイTシャツ屋さん",
	"The Mad Capsule Markets",
	"MAN WITH A MISSION",
	"Nothing's Carved In Stone",
	"Pay money To my Pain",
	"9mm Parabellum Bullet",
	"打ち首獄門同好会",
	"TK from 凛として時雨",
];
